Path:
  Input: ./src
  Output: ./dist
  Template: ./template

Site:
  Home_page_title: Home
  Prefix: ./
  Author: 54wedge
  Home_size: 3
  Time_style: '%B %d. %Y'
  Archive_group_by: month        # month / year / none

Content:
  Hide_meta: True
  Time_by: modify       # modify / create

Page_list:
  - _Home
  - Readme
  - _Archive
  - About
