Directory:
 Input: ./src/
 Output: ./dist/
 Module: ./module/
 Template: ./template/
 Post: ./src/post
 Archive: ./src/archive
 Asset: ./template/asset

Site:
 Prefix: ./
 Author: 54wedge

Ignore:   #ignore these pages when creating page
 Archive: archive
 #Category: category
 #Tag: tag

Config:
 Time_style: '%B %d. %Y'
 Hide_meta: False
 Archive_group_by: 'month'

Index:
 Page_size: 3
 Preview_line_count: 1
