Directory:
 Input: ./src
 Output: ./dist
 Template: ./template

Site:
 Prefix: ./
 Author: 54wedge

Config:
 Time_style: '%B %d. %Y'
 Hide_meta: True
 Archive_group_by: month        # month / year
 Save_style: str           # prettify / minify / str

Home:
 Page_size: 3

Page:
  - _Home
  - Readme
  - _Archive
  - About
