Directory:
 Input: ./src/
 Output: ./dist/
 Module: ./module/
 Template: ./template/
 Post: ./src/post
 Archive: ./src/archive
 Asset: ./template/asset

Site:
 Prefix: ./
 Author: 54wedge

Config:
 Time_style: '%B %d. %Y'
 Hide_meta: True
 Archive_group_by: month

Index:
 Page_size: 3

Page:
  - _Home
  - Todo
  - Readme
  - _Archive
